### ISSUE TITLE
Content licensing

### ISSUE THREAD

**Issue by riban-bw** [instatetragrammaton/Patches#1]
There is a clear statement in the readme that 

> patches have been built from scratch

Will you please expicitly state whether any content is used from the synth supplier? For example the factory content provided with the free version of Matt Tytel's Vital synth are not redistributable and hence any content, including wavetables from that content is similarly not distributable. I need to know so that I can be sure that I can include LV2 versions of your patches with software (like Zynthian).

Cheers!

**Comment by instatetragrammaton** [comment]
Hi!

That's a really good question and something I honestly did not consider. The problem is not made easier by the fact that:

1) I'm using the Pro version of Vital which means that I've got the full set of factory content so I never considered what could be missing
2) The wavetables don't have their authors directly attached to it (i.e. if I upload a patch with the "Clicky Robot" wavetable, it doesn't say that the WT was originally in the Factory Content)
3) Vital stores the wavetables inline in the patch, which means that even if you have the free version of Vital, you don't run into "this wavetable is missing" errors.

A quick scan of all the patches that I've currently uploaded show that a few of them use the content that is shipped with the Pro version - wavetables by Afro, Glorkglunk and the factory set. The rest use either init sines/saws and basic waveforms or TTWT, or homegrown WTs.

I will clarify what "from scratch" means and add a notification to the README. Apologies for the inconvenience.

**Comment by instatetragrammaton** [comment]
@riban-bw I've updated the [main README](https://github.com/instatetragrammaton/Patches/blob/master/README.md) and I've explicitly mentioned this issue in the [Vital README](https://github.com/instatetragrammaton/Patches/blob/master/Matt%20Tytel%20Vital/README.md).

I've also gone through the Vital patches that use simple sine, square and saw waves so that when it says "Init" you can be assured that there's no factory content in there.

Given that the source of Vital contains no wavetable content whatsoever, even the Factory WTs are problematic. However, changing something like "basic waveforms" feels to me like the sound design equivalent of putting copyright on a quicksort algorithm.

Please let me know if this resolves the issue for you :)

**Comment by riban-bw** [comment]
Although the basic content may appear simple, public domain type waveforms the effort to create a wavetable and any crafting required to make it work with Vital may constitute original art. I am not an expert but would be weary of this, especially as Matt has stated that wavetables distributed with the free license are not redistributable.

I cannot identify which patches use wavetables without first downloading them and loading into Vital which of course may contravene rights! For now I will assume I cannot use any of these. If you were able to tag them it may be useful. Not sure how, maybe adding a list as a separate document? I know this is work you didn't expect and probably don't want so feel free to tell me to go away but of course it would be great to be able to share some of your patches with the Zynthian audience.

**Comment by instatetragrammaton** [comment]
>  I know this is work you didn't expect and probably don't want so feel free to tell me to go away but of course it would be great to be able to share some of your patches with the Zynthian audience.

I made this repository explicitly to share knowledge and the more people can profit from it (by learning something), the better, so no - I will absolutely not tell you to go away :).

Additionally, the Zynthian project is really cool, so I'd definitely want to help it along - not block it! Thanks for bringing it to my attention.

Anyway - I've gone through all the Vital patches that are currently uploaded. I found 3 that I could not easily turn into ones that are fully free from factory content. I'll start with making my own basic wavetables and samples that I can upload to the repository separately. Thankfully, Audacity made generating white and pink noise really easy ;) All patches that I add from now on - if possible - will be created without any usage of the factory content. If that's not possible, they'll end up in the UsingFactoryContent folders.

I hope this resolves the issue!

**Comment by riban-bw** [comment]
That's great thanks for your effort and sorry to add unexpected work but we are all in a better place now ;-). I will probably go through them all again, converting to LV2 rather than try to identify the ones that have changed but that is a manual process so will take a little time. Do you want the LV2 versions here too? (Of course if you modify a patch the LV2 would be out of step!) I can convert the settings automatically but need to use the LV2 version of Vitalium to save the wavetable blobs - hence the manual process.

[Edit] I have added these to Zynthian [here](https://github.com/zynthian/zynthian-data/tree/master/presets/lv2/Vitalium_instatetragrammaton.lv2). Feel free to grab copies or link to them. They use the distrho vitalium LV2 URN. Cheers!

**Comment by instatetragrammaton** [comment]
> sorry to add unexpected work

This is a more sustainable way forward :)

Since the original Vital patches are just plain JSON (and Vitalbanks are just zipfiles, renamed) - I'm thinking it should just be possible to write something that converts these to LV2 format, perhaps a small Python script or so. The alternative would be a macro that (when Vitalium is running), loads the patch, saves the patch under a new name, and so on - less work, more time-consuming I guess ;)

Thank you!

**Comment by riban-bw** [comment]
I wrote a script to convert the controls to LV2 but the wavetables, etc. are a blob which needs more knowledge to create.
