### ISSUE TITLE
can you put all of your vital presets into one .vitalbank?

### ISSUE THREAD

**Issue by RustoMCSpit** [instatetragrammaton/Patches#4]

**Comment by instatetragrammaton** [comment]
The reason I haven't done this is because there's no overarching theme to the presets, and I'd have to update the bank every time I'd add a preset.

This should have all of 'm in there - https://www.mediafire.com/file/h0g6btezvl31k8z/AllPresets.vitalbank/file

However, as shown - you can download the entire repo as a .zip file and throw everything away that's not a .vital file :)

**Comment by RustoMCSpit** [comment]
is there a theme any of them are close to? you could try making vital presets with a theme in mind if you want to go down that route
